# Redirect root to login page
[[redirects]]
  from = "/"
  to = "/login"
  status = 302

# SPA routing - all other routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"