import React, { useState, useEffect } from 'react';
import { VideoAnalysisResult } from '../../services/openaiService';
import { generateScript } from '../../services/scriptGeneration.service';
import ShortVideoPlayer from './ShortVideoPlayer';

interface ContentSummaryScreenProps {
  analysisResult: VideoAnalysisResult;
  onGenerateScript: () => void;
  onCreateShort: () => void;
  showScript?: boolean;
}

const ContentSummaryScreen: React.FC<ContentSummaryScreenProps> = ({
  analysisResult,
  onGenerateScript,
  onCreateShort,
  showScript = false
}) => {
  const [revisedScript, setRevisedScript] = useState<string | null>(null);
  const [isGeneratingScript, setIsGeneratingScript] = useState(false);
  const [showShortPlayer, setShowShortPlayer] = useState(false);
  const [avatarPosition, setAvatarPosition] = useState<'left' | 'top'>('left');
  const [hasGeneratedOnce, setHasGeneratedOnce] = useState(false);

  const handleGenerateScriptClick = async () => {
    // First click: Show summary, key points, suggested edits (already displayed)
    if (!hasGeneratedOnce) {
      setHasGeneratedOnce(true);
      return; // Just mark that we've clicked, but don't generate yet
    }

    // Second click: Show the revised script (already generated by VideoAnalysisAgent)
    setIsGeneratingScript(true);
    setAvatarPosition('top');

    try {
      // The revised script is already in analysisResult.revisedScript
      // Extract the revised script text
      let scriptText = '';
      if (analysisResult.revisedScript) {
        if (typeof analysisResult.revisedScript === 'string') {
          scriptText = analysisResult.revisedScript;
        } else if (analysisResult.revisedScript.revisedScript) {
          scriptText = analysisResult.revisedScript.revisedScript;
        }
      }
      
      // Simulate processing time for better UX
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      setRevisedScript(scriptText || 'Revised script will appear here...');
      setIsGeneratingScript(false);
    } catch (error) {
      console.error('Error displaying revised script:', error);
      setIsGeneratingScript(false);
    }
  };

  const handleCreateShortClick = () => {
    setAvatarPosition('top');
    setShowShortPlayer(true);
  };

  if (showShortPlayer) {
    return (
      <ShortVideoPlayer
        analysisResult={analysisResult}
        onBack={() => setShowShortPlayer(false)}
      />
    );
  }

  return (
    <div className="min-h-screen bg-white">
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-6xl mx-auto">
          <div className={`grid grid-cols-1 ${avatarPosition === 'left' ? 'lg:grid-cols-3' : 'lg:grid-cols-1'} gap-8 items-start`}>
            {/* Avatar - Left or Top */}
            <div className={`flex ${avatarPosition === 'left' ? 'justify-start' : 'justify-center'} transition-all duration-700`}>
              <div className={`relative transition-all duration-700 ${
                avatarPosition === 'top' ? 'transform -translate-y-20 opacity-0' : 'transform translate-y-0 opacity-100'
              }`}>
                <div className="w-32 h-32 rounded-2xl overflow-hidden border-4 border-opacity-20" style={{ borderColor: '#11335d' }}>
                  <div className="w-full h-full flex items-center justify-center" style={{ backgroundColor: 'white' }}>
                    <img 
                      src="/images/team/mrgyb-ai.png"
                      alt="Mr. GYB AI"
                      className="w-full h-full object-cover"
                      onError={(e) => {
                        const target = e.target as HTMLImageElement;
                        target.style.display = 'none';
                        target.parentElement!.innerHTML = '<div class="w-full h-full flex items-center justify-center text-black text-2xl font-bold">GYB</div>';
                      }}
                    />
                  </div>
                </div>
                <div className="absolute inset-0 rounded-2xl border-2 border-yellow-400 pointer-events-none"></div>
              </div>
            </div>

            {/* Content - Right */}
            <div className={`${avatarPosition === 'left' ? 'lg:col-span-2' : 'lg:col-span-1'} space-y-6`}>
              {isGeneratingScript ? (
                <div className="flex flex-col items-center justify-center py-20">
                  <div className="relative w-16 h-16 mb-4">
                    <div className="absolute inset-0 border-4 border-navy-blue border-t-transparent rounded-full animate-spin"></div>
                  </div>
                  <p className="text-xl text-gray-700">Sit tight while I work my magic...</p>
                </div>
              ) : revisedScript || (showScript && hasGeneratedOnce) ? (
                <div className="space-y-6">
                  <h2 className="text-3xl font-bold text-black">
                    Here Is The Revised Script For Your Video!
                  </h2>
                  <div className="bg-green-50 border border-green-200 rounded-lg p-6">
                    <p className="text-lg text-gray-700 whitespace-pre-wrap leading-relaxed">
                      {revisedScript || (analysisResult.revisedScript && typeof analysisResult.revisedScript === 'string' 
                        ? analysisResult.revisedScript 
                        : analysisResult.revisedScript?.revisedScript) || 'Script generation in progress...'}
                    </p>
                  </div>
                  {/* Show the two buttons again below the script */}
                  <div className="flex flex-col sm:flex-row gap-4 pt-6">
                    <button
                      onClick={handleGenerateScriptClick}
                      disabled={isGeneratingScript}
                      className="px-8 py-4 text-black font-semibold rounded-lg transition-all duration-200 disabled:opacity-50 flex items-center justify-center"
                      style={{ backgroundColor: '#e0c472' }}
                    >
                      Generate a Script
                    </button>
                    <button
                      onClick={handleCreateShortClick}
                      disabled={isGeneratingScript}
                      className="px-8 py-4 text-white font-semibold rounded-lg transition-all duration-200 disabled:opacity-50 flex items-center justify-center"
                      style={{ backgroundColor: '#3b82f6' }}
                    >
                      Turn the video into a short
                    </button>
                  </div>
                </div>
              ) : (
                <>
                  {/* Summary */}
                  <div>
                    <h3 className="text-xl font-bold text-black mb-3">Summary</h3>
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                      <p className="text-lg text-black leading-relaxed">{analysisResult.summary}</p>
                    </div>
                  </div>

                  {/* Key Points */}
                  <div>
                    <h3 className="text-xl font-bold text-black mb-3">Key Points</h3>
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                      <ul className="space-y-3">
                        {analysisResult.keyPoints?.map((point, index) => (
                          <li key={index} className="flex items-start space-x-3">
                            <div className="bg-blue-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-bold flex-shrink-0 mt-1">
                              {index + 1}
                            </div>
                            <span className="text-gray-700">{point}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Suggested Edits */}
                  <div>
                    <h3 className="text-xl font-bold text-black mb-3">Suggested Edits</h3>
                    <div className="space-y-4">
                      {analysisResult.suggestedEdits?.map((edit, index) => (
                        <div key={index} className="bg-orange-50 border border-orange-200 rounded-lg p-4">
                          <h4 className="font-semibold text-orange-900 mb-2">{edit.title}</h4>
                          <p className="text-gray-700">{edit.description}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                </>
              )}

              {/* Action Buttons */}
              <div className="flex flex-col sm:flex-row gap-4 pt-6">
                <button
                  onClick={handleGenerateScriptClick}
                  disabled={isGeneratingScript}
                  className="px-8 py-4 text-black font-semibold rounded-lg transition-all duration-200 disabled:opacity-50 flex items-center justify-center"
                  style={{ backgroundColor: '#e0c472' }}
                >
                  Generate a Script
                </button>
                <button
                  onClick={handleCreateShortClick}
                  disabled={isGeneratingScript}
                  className="px-8 py-4 text-white font-semibold rounded-lg transition-all duration-200 disabled:opacity-50 flex items-center justify-center"
                  style={{ backgroundColor: '#3b82f6' }} // Blue button
                >
                  Turn the video into a short
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContentSummaryScreen;

